image: docker:git
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

# cache:
#   paths:
#     - node_modules/

# before_script:
#   - npm install

stages:
  - build

build:
  stage: build
  script:
    - docker login -u _json_key -p "$GCR_JSON_KEY" $REGISTRY
    - docker build -t $REGISTRY/$GPROJECT/$SERVICE:$CI_COMMIT_SHA .
    - docker tag $REGISTRY/$GPROJECT/$SERVICE:$CI_COMMIT_SHA $REGISTRY/$GPROJECT/$SERVICE:latest
    - docker push $REGISTRY/$GPROJECT/$SERVICE
  only:
    - master